# Site settings
title: Interactify
email: tas@interactify.dk
description: > # this means to ignore newlines until "baseurl:"
    Interactify template
url: "http://interactify.dk" # the base hostname & protocol for your site - used for feed.xml
twitter_username: Interactify
github_username:  interactify

collections:
  carrousel:
    output: false
  cases:
    output: false
  referencer:
    output: false
  awards:
    output: false
  about:
    output: false
  badges:
    output: false
  news:
    output: true
    permalink: /news/:title.html
  about:
    output: false
  contact:
    output: true
  social:
    output: false


defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
      

# Build settings
markdown: kramdown